stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - apt update
    - apt install curl -y
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
    - . "$HOME/.cargo/env"
    - rustup toolchain install nightly --profile complete
    - cargo build
  artifacts:
    paths:
      - target/debug/feigen
      - target/debug/kaki
      - target/debug/kiwi
      - target/debug/opfel

unit-test-job:
  stage: test
  script:
    - apt update
    - apt install curl -y
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
    - . "$HOME/.cargo/env"
    - rustup toolchain install nightly --profile complete
    - cargo test
