stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cargo build
  artifacts:
    paths:
      - target/debug/feigen
      - target/debug/kaki
      - target/debug/kiwi
      - target/debug/opfel

unit-test-job:
  stage: test
  script:
    - cargo test
