stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  needs: []
  tags: ["rust-nightly"]
  script:
    - cargo build
  artifacts:
    paths:
      - target/debug/feigen
      - target/debug/kaki
      - target/debug/kiwi
      - target/debug/opfel

unit-test-job:
  stage: test
  needs: []
  tags: ["rust-nightly"]
  script:
    - cargo test

lint-test-job:
  stage: test
  needs: []
  tags: ["rust-nightly"]
  script:
    - cargo clippy -- -Dwarnings
