[debug.databases.feigen]
url = "sqlite://tmp/feigen.sqlite"

[debug.databases.kiwi]
url = "sqlite://tmp/kiwi.sqlite"
template_dir = "templates"

[debug.databases.opfel]
url = "sqlite://tmp/opfel.sqlite"
template_dir = "templates"


