[package]
name = "pos"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5"
rocket_okapi = { version = "0.8", features = ["rapidoc"] }
schemars = "0.8"
rocket_db_pools = { version = "0.1", features = ["sqlx_sqlite"] }

serde = "1.0"
serde_json = "1.0"
