[package]
name = "kiwi"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls","sqlite" ] }
rustls = "0.23.5"
tokio = { version = "1.37.0", features = ["full"] }
